[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
castagne_backend = "DGv5FsFqJsmF5WN4sA5oa9hYp931fApi7ugRC66yEWE4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/castagne/*.ts"
create-player = "ts-node scripts/create_players.ts"
read-player = "ts-node scripts/read_players.ts"